import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import FooterConditional from '@/components/layout/footer-conditional';
import SocialBar from '@/components/layout/socialbar';
import { CartProviderWrapper } from '@/components/providers/CartProviderWrapper';
import CookieConsent from '@/components/ui/cookie-consent';

const tenorSans = localFont({
  src: '../public/fonts/tenorsans/TenorSans-Regular.ttf',
  variable: '--font-tenorsans',
  display: 'swap',
});

const cocoGothic = localFont({
  src: '../public/fonts/cocogothic/CocoGothic_trial.ttf',
  variable: '--font-cocogothic',
  display: 'swap',
});

const hatton = localFont({
  src: '../public/fonts/hatton/PP Hatton Medium 500.otf',
  variable: '--font-hatton',
  display: 'swap',
  weight: '500',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${tenorSans.variable} ${cocoGothic.variable} ${hatton.variable} flex flex-col min-h-screen`}>
        <CartProviderWrapper>
          <SocialBar />
          <main className="flex-1">
            {children}
          </main>
          <FooterConditional />
          <CookieConsent />
        </CartProviderWrapper>
      </body>
    </html>
  );
}
